### ISSUE TITLE
What is 'bert-large-uncased' in config setting?

### ISSUE THREAD

**Issue by dsbyprateekg** [pawangeek/Competitions-ML#1]
Hi,

I tried to run the bert+fastai code but getting following error-

`FileNotFoundError                         Traceback (most recent call last)
<ipython-input-42-da4e865a2336> in <module>
----> 1 bert_model = BertForSequenceClassification.from_pretrained(config.bert_model_name, num_labels=3)`

in config setting you have mentioned `bert_model_name="bert-large-uncased",`

From where I can get this? I have downloaded the bert-pretrained-weights from kaggle but did know which file to use here.

Can you please help on this?

**Comment by pawangeek** [comment]
Hello sir, there is no need to add any bert-pretained-weight manually
Just use these pytorch libraries with active internet connection.
Actually I don't have gpu that's why I prefer kaggle environment for my gpu based calculations. 

`from pytorch_pretrained_bert.modeling import BertConfig, BertForSequenceClassification`
`from pytorch_pretrained_bert import BertTokenizer`

**Comment by dsbyprateekg** [comment]
Thanks Pawan for your reply!

I have on the internet settings in kernel and now able to run your code.

Can you please also share the code for making the submission file?

**Comment by pawangeek** [comment]
Just put final.to_csv(submission.csv, index=false) at the end
